### ISSUE TITLE
[CHANGE] application/vnd.visio 

### ISSUE THREAD

**Issue by mvanleeuwen1** [patrickmccallum/mimetype-io#1]
# The mimetype affected
application/vnd.visio

# The change to make
Add  .vsdx

# Supporting link
(https://www.microsoft.com/en-us/microsoft-365/visio/flowchart-software)

**Comment by patrickmccallum** [comment]
Thanks for opening the issue! I've updated the mimeData.json and added the other file extensions in your link.

**Comment by mvanleeuwen1** [comment]
Thanks for the quick response.

Mark Van Leeuwen
System Administrator III
Associates of Cape Cod, Inc.
124 Bernard E. Saint Jean Drive
East Falmouth, MA 02536
(e) ***@***.***
(v)508.540.3444 EXT.1402
(m)508-685-8241
