### ISSUE TITLE
[CHANGE] add iso codec

### ISSUE THREAD

**Issue by uieonru** [patrickmccallum/mimetype-io#16]
# The mimetype affected
.iso file 

# The change to make
you should add it, it is basically a zip but it holds a dvd 

# Supporting link
https://mimetype.io/application/x-cd-image?source=browser

**Comment by patrickmccallum** [comment]
Interestingly its "official" mimetype appears to be application/x-iso9660-image according to https://www.loc.gov/preservation/digital/formats/fdd/fdd000348.shtml

I'll add a page for all of them. Thanks for the issue!
