### ISSUE TITLE
[ADD] application/x-diskcopy

### ISSUE THREAD

**Issue by YouTube-101** [patrickmccallum/mimetype-io#17]
# The mimetype affected
application/x-diskcopy

# The change to make
Add .dmg

# Supporting link
I got a 404 when I uploaded a dmg file. it's mime type is "application/x-diskcopy"

**Comment by luckv** [comment]
@YouTube-101 do you have more information about this mime type? I mean something like an official source, MDN web docs, RFCs, relevant GitHub issues.. something to link the extension .dmg to that exact mime type. I try to search the internet but I didn;t find anything.

**Comment by luckv** [comment]
@patrickmccallum I would close this issue, because there are no information about this mimetype and how to detect it.
