### ISSUE TITLE
[CHANGE] audio/vnd.wave is deprecated? I think not

### ISSUE THREAD

**Issue by luckv** [patrickmccallum/mimetype-io#18]
I see on the website that `audio/vnd.wave` is deprecated and should be used `audio/wav` instead. ([https://mimetype.io/audio/vnd.wave](https://mimetype.io/audio/vnd.wave))

I didn't find any information in the internet when and why that mimetype was deprecated, neither I found any information explaining that `audio/wav` is the official mimetype.

Instead I found comments that said that `audio/vnd.wave` is the official mime type for wav files.
I found an RFC, [RFC 2361](https://tools.ietf.org/html/rfc2361).
The comments I found:
- [https://stackoverflow.com/a/44827990/17387447](https://stackoverflow.com/a/44827990/17387447)
- [https://github.com/sindresorhus/file-type/pull/150#discussion_r199328984](https://github.com/sindresorhus/file-type/pull/150#discussion_r199328984)
- [https://github.com/jshttp/mime-db/issues/22#issuecomment-107128888](https://github.com/jshttp/mime-db/issues/22#issuecomment-107128888)

In compensation, neither mdn web docs, or IANA report `audio/vnd.wave` as a mimetype for wav files. IANA didn't report a mimetype for wav files at all.
- [MDN web docs](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types)
- [IANA audio media types](https://www.iana.org/assignments/media-types/media-types.xhtml#audio)

So, if you have reasons to say that `audio/vnd.wave` is deprecated, should be explained more in detail why, because there is so little information in the internet about this thing, and this beautiful site is the first result I found when searching '.wav official mime type' in google. 
Instead, if I was right, should be removed that banner. I can do a pull request if it's the right thing to do.

**Comment by patrickmccallum** [comment]
You're 100% right, looks like the "official" mimetype is `audio/vnd.wave` from what I can see too. 

The mimedata.json file auto flags alternatives as "deprecated", which is something that obviously should be fixed. #3 I think it's mentioned in this issue already. I'll go add a new array such as "preferred" with a more appropriate banner text if you think that would be a good solution.

Thanks for bringing it up.

**Comment by luckv** [comment]
Fantastic, I appreciate your work on this project.

I want to share with you and this project what I have experienced in these days with this mime type.

I'm working on a backend project that uses a library to check the correct mime type of binary files to be then previewed in browsers. That library returns the format `audio/vnd.wave` for wav files. Despite that being the 'official' and correct mime type, all browsers I tested that mime type with (Chrome, Firefox and Safari) can't preview using the `<audio>` tag. But if I change the mime type to `audio/wav`, then the preview works, in all browsers....   

Not much surprised because this behaviour complies with MDN web docs.

So my final consideration is that all browser vendors decided to not support `audio/vnd.wave` mime type, but instead they all support `audio/wav`. And also when I upload a `.wav` file on your site, the displayed mime type is that... I suppose because there is an internal api of the browser that return the mime type, or maybe you check the magic numbers of the file with an external library. Anyway, it's all coherent. Starting all from MDN web docs, the 'RFCs wiki' for web developers.

My question is, have all the browsers vendors made the `audio/wav` the de-facto officially supported mime type? Why MDN web docs and the vendors decided this and they have gone against an RFC, even if so old that is from 1998?

At the end I found the answer to my question, because **that RFC is informational**, reporting the exact words: 
> does not represent an Internet community consensus or recommendation

**Comment by patrickmccallum** [comment]
Thanks @luckv I'll add something to the page about this and also to the links of the page. Was just about to publish the new version of the mimedata with the changes but I'll also build in a "Popular implementation differs from specification" flag/notice.

**Comment by luckv** [comment]
@patrickmccallum maybe you can add a link to an RFC if present. I don't if it's possible, but would be useful if near the RFC label there will be the RFC status, that like in this case is informational.

**Comment by patrickmccallum** [comment]
@luckv Sounds good. You can see the changes so far here: https://mimetype.io/audio/vnd.wav

Let me know if that's more clarifying than what we had before!

**Comment by luckv** [comment]
Seems perfect for me!

**Comment by patrickmccallum** [comment]
Awesome! Thanks for the issue, big improvement from this one :)

**Comment by hugovk** [comment]
By the way, https://mimetype.io/audio/vnd.wave now says `audio/vnd.wav` (no `e`) is preferred.

Should it say `audio/vnd.wave` (with `e`) is preferred?

**Comment by luckv** [comment]
@hugovk I agree with you.
@patrickmccallum Where does `audio/vnd.wav` (without `e`) come from, and why is it preferred? [RFC 2361](https://tools.ietf.org/html/rfc2361) mentions only `audio/vnd.wave` (with `e`), and I remember for all, that is only an **informational RFC**

Also I have a personal confusion about the meaning of the terms 'Preferred' and 'Popular'. What do they means?

Maybe with 'Popular' you mean this: 

> "Popular implementation differs from specification"

Then you should explain somewhere in the website what the flag means, not all people are fanatic like me of this repo 😝 

Anyway, @patrickmccallum I appreciate very much your work on this project, the website it's so simple but very useful 🚀
