### ISSUE TITLE
Trasforma file image

### ISSUE THREAD

**Issue by Mjcloclo79** [patrickmccallum/mimetype-io#27]
![Elena 20180510_1225111](https://github.com/patrickmccallum/mimetype-io/assets/121665846/a062d8d7-6e84-452e-b89e-7f53f21e7db4)
# The mimetype affected
Please enter the mimetype here

# The change to make
Add/remove/change description or link, etc

# Supporting link
A link to somewhere that authoritatively says why this change should be made

**Comment by patrickmccallum** [comment]
I'm guessing this is probably a request for a converter. Probably outside of the scope, if you're on mac you can convert by exporting the file again after opening it in preview.
