### ISSUE TITLE
[CHANGE] text/markdown is not deprecated

### ISSUE THREAD

**Issue by danielksb** [patrickmccallum/mimetype-io#31]
# The mimetype affected
text/markdown
text/x-markdown

# The change to make
The information about the deprecation status of markdown is upside down.
According to https://www.rfc-editor.org/rfc/rfc7763.html the registerd mimetype for markdown is `text/markdown`.
The extension prefix "x-" is deprecated as a best practice, see https://www.rfc-editor.org/bcp/bcp178.txt.

# Supporting link
The official mimetype for markdown is "text/markdown" according to [IANA](https://www.iana.org/assignments/media-types/media-types.xhtml).

**Comment by patrickmccallum** [comment]
You are completely correct, thank you for pointing this out. Looks like the type was duplicated in mimeData.json. I'll pen in running some code to detect other contradictions and will go fix them. 

Fix is deploying as I type.
