### ISSUE TITLE
[CHANGE] mimetype/here

### ISSUE THREAD

**Issue by janseris** [patrickmccallum/mimetype-io#32]
These two files are not possible to detect when file extension is removed in Windows.
Original extension is: xlsx
[excel2.xlsx](https://github.com/user-attachments/files/15972404/excel2.xlsx)
[excel1.xlsx](https://github.com/user-attachments/files/15972405/excel1.xlsx)

**Comment by patrickmccallum** [comment]
Unfortunately since this is your browser doing the detecting, without the file type and any detection it's able to do on its own it won't be able to detect the mimetype. Every OS/browser has its own methods/fallbacks for handling mimetype detection so the issue would have to be raised with them.
