### ISSUE TITLE
[CHANGE] deprecate application/x-sqlite3 in favor of application/vnd.sqlite3

### ISSUE THREAD

**Issue by rickyson96** [patrickmccallum/mimetype-io#40]
# The mimetype affected
`application/x-sqlite3` and `application/vnd.sqlite3`

# The change to make
Deprecate `application/x-sqlite3` and make `application/vnd.sqlite3` the preferred one.

# Supporting link
https://www.iana.org/assignments/media-types/application/vnd.sqlite3

**Comment by patrickmccallum** [comment]
You're correct, thank you.
