### ISSUE TITLE
[CHANGE] image/avif

### ISSUE THREAD

**Issue by cainmagi** [patrickmccallum/mimetype-io#44]
# The mimetype affected

[`image/avif` :link:](https://mimetype.io/image/avif)

# The change to make

The following reference link refers to a non-existing page.

https://github.com/patrickmccallum/mimetype-io/blob/a1136a4e57daf26ec4c0836c511e838457f6d8d1/src/mimeData.json#L98-L100

The link `image/avif-sequence` (`.avifs`) is already described on the page `image/avif`. The simplest way to tackle this issue is to remove this link.

# Alternative solutions

1. To make the mimetype `image/avif-sequence` searchable (currently it is not searchable and not listed), it may be better to split `.avifs` to a new `image/avif-sequence` page. If this option is preferred, it is better to create a new mimetype item rather than removing this link.
2. Make the link `image/avif-sequence` marked as "AKA" and redirected to the `image/avif`, like how [this page](https://mimetype.io/audio/x-aiff) works.

# Supporting link

N/A

**Comment by patrickmccallum** [comment]
I've fixed the dead link and made it clear they're separate I hope. Thanks!
