### ISSUE TITLE
[CHANGE]+mimetype/here

### ISSUE THREAD

**Issue by slippery22** [patrickmccallum/mimetype-io#6]
# The mimetype affected
Please enter the mimetype here

# The change to make
Add/remove/change description or link, etc

# Supporting link
A link to somewhere that authoritatively says why this change should be made

**Comment by patrickmccallum** [comment]
![image](https://github.com/patrickmccallum/mimetype-io/assets/11825795/202bd02e-e975-4c56-945e-2bf8789ad3b7)
