### ISSUE TITLE
[CHANGE] video/mp4

### ISSUE THREAD

**Issue by jakeparis** [patrickmccallum/mimetype-io#9]
# The mimetype affected
video/mp4 : specifically, I'm trying to confirm an mp4 file

# The change to make
Correctly identify these file types, instead of 404ing

# Supporting link
..?

**Comment by patrickmccallum** [comment]
What URL does your browser take you to when you drop in an MP4 file? MP4 is on the site at https://mimetype.io/video/mp4 but if you're not being taken there it's because your browser/computer likely isn't identifying it correctly.

**Comment by jakeparis** [comment]
You are correct. My browser works with a known mp4 file. I think it was a corrupt file. Thank you.
